### ISSUE TITLE
ant build setup

### ISSUE THREAD

**Issue by ghost** [marpies/onesignal-ane#4]
What is required on my device to run ant successfully from the build folder to replace icons, currently i have AIR SDK 23 and latest ant and gradle ?

btw link mentionned in
https://github.com/marpies/onesignal-ane/blob/master/actionscript/src/com/marpies/ane/onesignal/OneSignal.as
for postNotification method is now at
https://documentation.onesignal.com/reference#create-notification

**Comment by marpies** [comment]
Hi @spanvega,

You need to specify path to AIR and gradle in `build.properties` file, and also have Xcode command line tools installed to properly rebuild the extension with the new icons in place.

Is there any specific error you're getting when building the extension with the provided script?

**Comment by ghost** [comment]
hi again, build.properties was edit as follow

name = OneSignal
packageName = com.marpies.ane.onesignal

flex.sdk = C:/SDK/AIR

bin.ext =

ios.sdkversion = iphoneos

gradle.exec = C:/Program Files (x86)/gradle

---

ant command : 

C:\Users\spanvega\Desktop\onesignal-ane-master\build>ant
Buildfile: C:\Users\spanvega\Desktop\onesignal-ane-master\build\build.xml

swc:

BUILD FAILED
C:\Users\spanvega\Desktop\onesignal-ane-master\build\build.xml:116: Execute failed: java.io.IOException: Cannot run program "C:\SDK\AIR\bin\compc" (in directory "C:\Users\spanvega\Desktop\onesignal-ane-master\build"): CreateProcess error=193, %1 is not a valid Win32 application
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at java.lang.Runtime.exec(Runtime.java:620)
        at org.apache.tools.ant.taskdefs.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:58)
        at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:426)
        at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:440)
        at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:629)
        at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:670)
        at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:496)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
        at org.apache.tools.ant.Main.runBuild(Main.java:854)
        at org.apache.tools.ant.Main.startAnt(Main.java:236)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)
Caused by: java.io.IOException: CreateProcess error=193, %1 is not a valid Win32 application
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
        at java.lang.ProcessImpl.start(ProcessImpl.java:137)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 24 more

Total time: 0 seconds

otherwise everything i've tried from what's available from OneSignal console and your ANE worked fine

**Comment by dnikolaev** [comment]
Hi @spanvega,

You use Window, so you should add bin.ext = .exe

Please look carefully at the error description.

**Comment by marpies** [comment]
Hi @spanvega,

I forgot to mention what @dnikolaev said. If you're on Windows you also need to set `bin.ext` variable - I believe it should be either `.exe` or `.bat`.

**Comment by ghost** [comment]
as well with .bat or .exe the build failed

---

otherwise i have notice a strange behavior with buttons when using postNotification method

first i grab the user_id

OneSignal.idsAvailable (callback_token);

private function callback_token (oneSignalUserId : String, pushToken : String) : void
{
    user_id = oneSignalUserId;
}

when user has his id, app can notify

var parameters : Object =
{
        app_id : ONE_SIGNAL_APP_ID,
        include_player_ids : [user_id],
        send_after : newTime.toString (),
        data : { referral : 'discount', amount : 10},
        buttons : [{id : 'id_1', text : 'Continuer'},
                                {id : 'id_2', text : 'Visiter'}],
        headings : {en : 'Title In English', fr : 'Titre en Français'},
        contents : {en : 'Message In English', fr : 'Message en Français'}
};

OneSignal.postNotification (parameters, callback_push);

the result is 

notification outside app displays 2 buttons

http://img4.hostingpics.net/pics/258049noutside.png

notification inside app displays 3 buttons

http://img4.hostingpics.net/pics/978545ninside.png

OK button is pretty unexpected

in both cases debug traces 2 buttons

Buttons : [object OneSignalNotificationButton],[object OneSignalNotificationButton]

**Comment by marpies** [comment]
Are you getting the same error when you set `bin.ext`? The build works fine on my Windows machine when the variable is set to `.bat`.

As for the `postNotification` issue with buttons -  I'm not in control of that behavior, it's handled by OneSignal SDK.

**Comment by ghost** [comment]
hi, about buttons, no surprise, thought first it was an sdk issue, but ask anyway

concerning the build here is the result with .bat

C:\Users\spanvega\Desktop\onesignal-ane-master\build>ant
Buildfile: C:\Users\spanvega\Desktop\onesignal-ane-master\build\build.xml

swc:
    [mkdir] Created dir: C:\Users\spanvega\Desktop\onesignal-ane-master\build\temp\swc\content
     [exec] Using AIR SDK: C:/SDK/AIR
     [exec] Loading configuration: C:\SDK\AIR\frameworks\flex-config.xml
     [exec]
     [exec] 9000 bytes written to C:\Users\spanvega\Desktop\onesignal-ane-master\build\temp\swc\OneSignal.swc in 2,121 seconds
    [unzip] Expanding: C:\Users\spanvega\Desktop\onesignal-ane-master\build\temp\swc\OneSignal.swc into C:\Users\spanvega\Desktop\onesignal-ane-master\build\temp\swc\content
     [copy] Copying 1 file to C:\Users\spanvega\Desktop\onesignal-ane-master\bin
     [copy] Copying 1 file to C:\Users\spanvega\Desktop\onesignal-ane-master\build\temp\ios
     [copy] Copying 1 file to C:\Users\spanvega\Desktop\onesignal-ane-master\build\temp\android
     [copy] Copying 1 file to C:\Users\spanvega\Desktop\onesignal-ane-master\build\temp\default

ios:
    [mkdir] Created dir: C:\Users\spanvega\Desktop\onesignal-ane-master\build\temp\ios\build

BUILD FAILED
C:\Users\spanvega\Desktop\onesignal-ane-master\build\build.xml:23: Execute failed: java.io.IOException: Cannot run program "xcodebuild" (in directory "C:\Users\spanvega\Desktop\onesignal-ane-master\ios"): CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at java.lang.Runtime.exec(Runtime.java:620)
        at org.apache.tools.ant.taskdefs.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:58)
        at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:426)
        at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:440)
        at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:629)
        at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:670)
        at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:496)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
        at org.apache.tools.ant.Main.runBuild(Main.java:854)
        at org.apache.tools.ant.Main.startAnt(Main.java:236)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
        at java.lang.ProcessImpl.start(ProcessImpl.java:137)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 24 more

sorry can't help much to fix it, never get involved in ANE dev

**Comment by marpies** [comment]
Right, now the error is because there are no Xcode build tools on Windows. I have added prebuilt iOS library to the repository, pull the latest commit and run `ant swc android package`.

**Comment by ghost** [comment]
thanks for the effort Marcel, but still don't work, problem related to gradle.exec, should i point to something specific instead of root or bin folder

**Comment by marpies** [comment]
Hi @spanvega,

Yes, you need to specify path to the gradle executable that's in the bin folder, e.g. `gradle-2.14.1/bin/gradle`

**Comment by ghost** [comment]
gradle is defined correctly, however there's still a problem

C:\Users\spanvega\Desktop\onesignal-ane-master\build>gradle -v

---

## Gradle 3.1

Build time:   2016-09-19 10:53:53 UTC
Revision:     13f38ba699afd86d7cdc4ed8fd7dd3960c0b1f97

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_102 (Oracle Corporation 25.102-b14)
OS:           Windows 10 10.0 x86

C:\Users\spanvega\Desktop\onesignal-ane-master\build>ant swc android package
Buildfile: C:\Users\spanvega\Desktop\onesignal-ane-master\build\build.xml

swc:
    [mkdir] Created dir: C:\Users\spanvega\Desktop\onesignal-ane-master\build\temp\swc\content
     [exec] Using AIR SDK: C:/SDK/AIR
     [exec] Loading configuration: C:\SDK\AIR\frameworks\flex-config.xml
     [exec]
     [exec] 9000 bytes written to C:\Users\spanvega\Desktop\onesignal-ane-master\build\temp\swc\OneSignal.swc in 1,399 seconds
    [unzip] Expanding: C:\Users\spanvega\Desktop\onesignal-ane-master\build\temp\swc\OneSignal.swc into C:\Users\spanvega\Desktop\onesignal-ane-master\build\temp\swc\content
     [copy] Copying 1 file to C:\Users\spanvega\Desktop\onesignal-ane-master\bin
     [copy] Copying 1 file to C:\Users\spanvega\Desktop\onesignal-ane-master\build\temp\ios
     [copy] Copying 1 file to C:\Users\spanvega\Desktop\onesignal-ane-master\build\temp\android
     [copy] Copying 1 file to C:\Users\spanvega\Desktop\onesignal-ane-master\build\temp\default

android:

android-build:

BUILD FAILED
C:\Users\spanvega\Desktop\onesignal-ane-master\build\build.xml:61: The following error occurred while executing this line:
C:\Users\spanvega\Desktop\onesignal-ane-master\build\build.xml:69: Execute failed: java.io.IOException: Cannot run program "C:\DEV\gradle-3.1\bin\gradle" (in directory "C:\Users\spanvega\Desktop\onesignal-ane-master\android"): CreateProcess error=193, %1 is not a valid Win32 application

**Comment by marpies** [comment]
Hi @spanvega,

Ok, so the variable must point to `gradle.bat` that is in the `bin` directory.
